# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-08 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sixthings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='done',
            field=models.NullBooleanField(choices=[(False, 'No'), (True, 'Yes'), (None, 'Deferred')], default=False),
        ),
    ]
